### ISSUE TITLE
Please use more simple (and readable) solution

### ISSUE THREAD

**Issue by vitalk** [MaximPodrez/LeverX_Task_1#1]
https://github.com/MaximPodrez/LeverX_Task_1/blob/4d77f6bb7d656695c6cf920b779a47ade60b1391/DataMerger.py#L19

**Comment by MaximPodrez** [comment]
Changed on this:

room = self.rooms_with_students[str(student['room'])]
room['students'][str(student['id'])] = {
    'name': student['name']
}
