### ISSUE TITLE
Please use argparse for argument processing and validation

### ISSUE THREAD

**Issue by vitalk** [MaximPodrez/LeverX_Task_1#2]
https://github.com/MaximPodrez/LeverX_Task_1/blob/4d77f6bb7d656695c6cf920b779a47ade60b1391/main.py#L30

**Comment by MaximPodrez** [comment]
Changed on this:

parser = argparse.ArgumentParser(description='Merge rooms and students script')
parser.add_argument('-students', action="store", dest="students")
parser.add_argument('-rooms', action="store", dest="rooms")
parser.add_argument('-type', action="store", dest="type")
args = parser.parse_args()
start(args.students, args.rooms, args.type)
